Fix TypeError exception during cancel stack update
TypeError: call() takes exactly 3 arguments(5 given) is raised
during cancel stack update, this patch will fix the problem.

Change-Id: If85389150a15575d9e01466d950f8c07b8fa2717
Closes-Bug: #1448384
(cherry picked from commit 72403962033d15bfe910eae14f01a4461d1789e9)