"version" section should be required in template
"HeatTemplateFormatVersion" as default while a template missing version
section now in heat. But then the server can't parse the template in right
way, not translate hot format to cfn. Some errors raised such as:
  Error : At least one Resources member must be defined.
  but "resources" section has one resource.
  Error: The Parameter (image_id) was not defined in template.
  but "image_id" was defined in "parameter" section.

So if we cannot determine the template version, we should raise an
exception. This patch will check whether version section is in template,
if not we should raise exception.

Change-Id: Idc2ba2b9ae099d4509dfd81914aa9bb8bd3bfefb
Closes-Bug: #1267735