Fix default raw_template files value in migration
This was causing the following error when trying to do a stack-list:
ERROR: Attribute 'files' does not accept objects of type <type 'unicode'>

Change-Id: Ideee81e44e85fcd8d8f3c9c196702a6c78e5adfd
Closes-Bug: #1277278