Use empty list in list_join for validation
Calling list_join on the list of ResourceGroup's attributes in a
SoftwareConfig fails during template validation with:

ERROR: Property error : my_config: config "list_join" must operate on a
list

Closes-Bug: 1358831
Change-Id: I39d2da7a28ba53fbe3a95bff0198fa5c2f87aa3b
(cherry picked from commit 61a9d167c0f36a2846e39fd33a77ce2755801fe6)