Fix backtrace when using loadbalancer
Loadbalancer incorrectly tried to reference a string as an integer.

This resulted in the following typeerror which is repaired by
thi patch:

    timeout_check = 'timeout check %ds' % (health_chk['Timeout'])
TypeError: %d format: a number is required, not unicode

Fixes issue #240

Change-Id: I7e2697200d3fa9b0cb009f3a7898d487b70fc23a
Signed-off-by: Steven Dake <sdake@redhat.com>