Followup to I7736373d03c23884158e4a1d41defafb4e2b8a4c
that patch erroneously replaced dict.values() with dict.items(),
and now ExtraRouteSet can not be created due to AttributeError
('tuple' has no attribute 'has_interface').

Story: 2010142
Task: 45778
Change-Id: I2643b319f3a91f98097b96639f7298b25724aa62
(cherry picked from commit 65a68d97d0b0a4a78c2d21f6b76c6f207c993a19)